### ISSUE TITLE
great component, please add touch for mobile

### ISSUE THREAD

**Issue by born2net** [Alberplz/angular2-color-picker#1]
great component, please add touch for mobile
in mobile can't drag any of the points.

tx

Regards,

Sean
Checkout the Ultimate Angular 2 Boorstrap App: @ http://ng2.javascriptninja.io
Source@ https://github.com/born2net/ng2Boilerplate

**Comment by Alberplz** [comment]
Added support for mobile ,

thanks

**Comment by born2net** [comment]
works great tx
