### ISSUE TITLE
Upgrade to Angular 2 RC1

### ISSUE THREAD

**Issue by jhiemer** [Alberplz/angular2-color-picker#10]
Are there any plans for the upgrade to RC1?

**Comment by Alberplz** [comment]
Yes, now is updated

**Comment by jhiemer** [comment]
Have you created a new release?

**Comment by Alberplz** [comment]
Of course

**Comment by jhiemer** [comment]
thx.

**Comment by jhiemer** [comment]
Please excuse the interruption again: is it automatically published to npm?

**Comment by Alberplz** [comment]
No, but now is published ;)
