### ISSUE TITLE
Dialog height only being set once.

### ISSUE THREAD

**Issue by smatthews1999** [Alberplz/angular2-color-picker#110]
![image](https://cloud.githubusercontent.com/assets/562964/26603380/ae2fed16-4554-11e7-8510-b77766b10d9f.png)

https://github.com/rvmoldova/angular4-color-picker/blob/master/src/color-picker.directive.ts#L388

I am getting the variable 'dialogHeight' on the above line set only once on the first call, but not set on subsequent calls.

**Comment by wartab** [comment]
This package is no longer maintained by its owner. The package you are linking to is angular4-color-picker. I personnally recommend using ngx-color-picker. That one is actually maintained and should mostly be compatible with angular2-color-picker! Please also provide, if you still have the issue, a way to reproduce this issue.

**Comment by smatthews1999** [comment]
Thanks I will give that a try.
