### ISSUE TITLE
angular2-color-picker as an npm dependency -> not working

### ISSUE THREAD

**Issue by Csini** [Alberplz/angular2-color-picker#12]
Solution would be something like this here: https://github.com/Alberplz/angular2-color-picker/pull/11

**Comment by Alberplz** [comment]
Thank you very much Csini,  now I'm outside and I have no access to my latop, but I'll update the code as soon as I can. 
...and yes, I want this project would be an active one :)

**Comment by Csini** [comment]
Hello Alberplz! How are you? Are you still outside?

**Comment by Csini** [comment]
@Alberplz Something went wrong with the merge #11 ! I don't see any changes in your master (you forgot to push?) and the package  (2.0.0), which is uploaded to npm.js is also wrong, I get

ERROR in ./~/angular2-color-picker/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./lib/index.js in /home/csini/work/dailymenuboard/node_modules/angular2-color-picker
@ ./~/angular2-color-picker/index.js 10:9-34

**Comment by Alberplz** [comment]
Hi, I've updated the package for ng2 rc5, the lib can be generated with gulp (still some changes pending...)

**Comment by Alberplz** [comment]
Now the color-color picker template is in a separated directory, it would be nice having several templates to choose.

**Comment by Csini** [comment]
Thank you!
