### ISSUE TITLE
Cannot read property 'a' of undefined

### ISSUE THREAD

**Issue by vistajess** [Alberplz/angular2-color-picker#121]
Sometimes it works fine, but sometimes it doesnt due to this issue.

What seems to be a problem on this case??

![image](https://user-images.githubusercontent.com/12708502/32779898-5df405c6-c97a-11e7-9e39-8e223958da50.png)

here's my code: 

![image](https://user-images.githubusercontent.com/12708502/32779934-7d4f691a-c97a-11e7-98c5-a3c36b47fae1.png)

Suggestions will be highly appreciated.

**Comment by wartab** [comment]
This package is unmaintained and hasn't been updated for almost a year now. Use this package instead: https://github.com/zefoy/ngx-color-picker

**Comment by vistajess** [comment]
Thanks bro

**Comment by vistajess** [comment]
Dang! Im addressing to wrong package. my bad


![image](https://user-images.githubusercontent.com/12708502/32798352-6056a3ac-c9af-11e7-97b6-f7e7660d4ca5.png)
