### ISSUE TITLE
Feature Request: Use the picker without dropdown

### ISSUE THREAD

**Issue by SebastianStehle** [Alberplz/angular2-color-picker#13]
Hi, I would like to use the color picker without a dropdown and a button. Are there any plans?

**Comment by Csini** [comment]
Hello!

Can you describe with more detail, how you want to use the color picker widthout the dropdown and button? Do you want to just be able to write the hex code of color inside the input field?

**Comment by SebastianStehle** [comment]
I am programming a diagram editor. I would like to have a color picker on the right side, where I can change the color of the selected object(s). Similar to inkscape: http://www.macworld.co.uk/download/design-illustration/inkscape-091-3214166/
