### ISSUE TITLE
Feature Request: "OK" button to confirm selection

### ISSUE THREAD

**Issue by nironater** [Alberplz/angular2-color-picker#15]
**Main Request:**
Add `[cpOKButton]` (To add the "OK" button like you done for "Cancel" button).

**Comments:**
- I think it would be very easy to add as i guess all it should do is close the dialog (as apposed to the cancel button reverting to the previous color)
- It's a bit weird for me to think that in the current situation in order to confirm my selection i need to click somewhere else in the window, did i miss something?

**Bonus:**

- Add `[cpOKButtonText]` (To change the text of the button)
- Add `[cpOKButtonClass]` (To add the "OK" button class for design purpose)

Thanks ahead and nice work!

**Comment by Alberplz** [comment]
HI
I would also add an extra option to define the behaviour when user clicks out:
[onClickOut]=revert/change
So we can have all combinations
Thanks!
