### ISSUE TITLE
Merging forked project and packaging for npm

### ISSUE THREAD

**Issue by BrainCrumbz** [Alberplz/angular2-color-picker#17]
Hi there

we noticed there's a fork of this project at [bbbenja/angular2-color-picker](https://github.com/bbbenja/angular2-color-picker), which seems mainly centered around cleaning up sources in repository, keeping up-to-date with dependencies, making library available to npm. Unfortunately issues are closed there.

Then there's also an open PR #11 here, still aiming to have an npm package.

Is there any chance to join all those efforts, better under a single project, so to have basically **the** angular 2 color-picker? Thanks

**Comment by Csini** [comment]
same issue as https://github.com/Alberplz/angular2-color-picker/issues/12
