### ISSUE TITLE
Use of window and document

### ISSUE THREAD

**Issue by jimitndiaye** [Alberplz/angular2-color-picker#2]
This is a great little component. I was already dreading having to write one from scratch. 
I am a but concerned about the frequent use of the '''window''' and ```document``` globals however which would limit the components use in web workers for instance where you don't have access to the DOM. Couldn't the event listeners be attached in other ways?

**Comment by Alberplz** [comment]
Yes, it would be nice. Maybe with samething like that: host: { '(document:click)': 'onClick()'}, although directive still is using nativeElement
