### ISSUE TITLE
Doesnt work with Angular 2 RC 6 - Please add support for NgModule

### ISSUE THREAD

**Issue by naveedahmed1** [Alberplz/angular2-color-picker#28]
The plugin doesn't seem to work with Angular 2 RC 6, please add support for NgModule.

**Comment by lordpiti** [comment]
There is already a pull request for this. I downloaded the code and it works

**Comment by mlessio** [comment]
I have also tested the code from @AsianPsychoBoy and it works like a charm. Please @Alberplz  pull from his repo.

**Comment by naveedahmed1** [comment]
@Alberplz when should we expect new release with these changes?

**Comment by Alberplz** [comment]
Updated to RC6

**Comment by naveedahmed1** [comment]
@Alberplz Great :+1:
