### ISSUE TITLE
toggle open close

### ISSUE THREAD

**Issue by daniele-zurico** [Alberplz/angular2-color-picker#32]
Is possible to toggle the color picker? I don't know how I can close the color Picker.
Or have an event to manage it

**Comment by Alberplz** [comment]
Not yet implemented.

**Comment by daniele-zurico** [comment]
Well I look on your code and it's quite easy to implement it. Just change the open function to a toggle function and put an if statement on isOpen and in case call close. I already did it and it works great

**Comment by Alberplz** [comment]
I was writing samething too

**Comment by Alberplz** [comment]
When you click in the html element the color picker opens and when you click outside closes. 
Do you want know if the dialog is open? Also control the dialog from a variable?
[(togle)]="varToggle"?

**Comment by webtrix** [comment]
I would maybe also add an option to add a "close button" in the color-picker dialog, some people don't know they can close the dialog just by clicking outside of the dialog.
