### ISSUE TITLE
[TSC ERROR]

### ISSUE THREAD

**Issue by mcwebdev** [Alberplz/angular2-color-picker#4]
Thanks for making this, works great! I do see some tsc compile errors. I tried typings install.

app/views/service/color-picker/color-picker.directive.ts(142,23): error TS2339: Property 'pageX' does not exist on type 'Event'.
app/views/service/color-picker/color-picker.directive.ts(142,51): error TS2339: Property 'pageX' does not exist on type 'Event'.
app/views/service/color-picker/color-picker.directive.ts(142,65): error TS2339: Property 'touches' does not exist on type 'Event'.
app/views/service/color-picker/color-picker.directive.ts(145,23): error TS2339: Property 'pageY' does not exist on type 'Event'.
app/views/service/color-picker/color-picker.directive.ts(145,51): error TS2339: Property 'pageY' does not exist on type 'Event'.
app/views/service/color-picker/color-picker.directive.ts(145,65): error TS2339: Property 'touches' does not exist on type 'Event'.

**Comment by Alberplz** [comment]
Thanks, errors deleted in this new version
