### ISSUE TITLE
a.Rgba is not a constructor (angular 2 release + webpack)

### ISSUE THREAD

**Issue by forik** [Alberplz/angular2-color-picker#41]
Using angular 2 release version with weback getting error "a.Rgba is not a constructor".
Seems like #38 should resolve the issue. 

**Update**
Issue appears only with minified code
```
new UglifyJsPlugin({
        beautify: false, //prod
        mangle: { screw_ie8 : true, keep_fnames: true }, //prod
        compress: { screw_ie8: true }, //prod
        comments: false //prod
    }
```

**Comment by forik** [comment]
I was importing a module in a wrong way. Closing the issue

**Comment by madebysoren** [comment]
Hi @forik. I'm experiencing the same; how did you resolve this issue?

**Comment by forik** [comment]
@madebysoren I don't remember what exactly caused the problem. Referring to the comment that I left above seems like that it was an import problem. This is how I am importing it now:
`import { ColorPickerModule } from 'angular2-color-picker';`
And in module:
```
imports: [
        CommonModule,
        FormsModule,
        ColorPickerModule
    ]
```
