### ISSUE TITLE
Upgrade to NG 2.0.2 (or 2.1.0-rc.0) causes: Unexpected value 'ColorPickerDirective' declared by the module 'AppModule'

### ISSUE THREAD

**Issue by gatapia** [Alberplz/angular2-color-picker#44]
The last commit to angular2-color-picker (1.2.1) fixed NG 2 new module issues and webpack issues.  However, the latest NG update (2.0.2) appears not to recognise the color picker.

I am using angular cli (webpack) for build.

**Comment by PoppyPham** [comment]
I got this before, dont need declare ColorPickerDirective in AppModule, just import to your component.

**Comment by Alberplz** [comment]
There was a mistake in the docs. Updated in the last version
