### ISSUE TITLE
[TSC ERROR] Getting ElementRef error on latest angular upgrade 2.0.0-beta.17

### ISSUE THREAD

**Issue by mcwebdev** [Alberplz/angular2-color-picker#6]
Hi,
I am getting new error on latest ng2 upgrade.

It doesn't seem to like `this.el`

**color-picker.directive.ts line 40 **

`this.dcl.loadNextToLocation(DialogComponent, this.el)`

`Severity	Code	Description	Project	File	Line	Suppression State
Error	TS2345	Argument of type 'ElementRef' is not assignable to parameter of type 'ViewContainerRef'.
  Property 'element' is missing in type 'ElementRef'.	TypeScript Virtual Projects	\views\service\color-picker\color-picker.directive.ts	40	Active
`

**Comment by Alberplz** [comment]
Hi,
Last version is updated for ng2 Beta 17:
https://github.com/Alberplz/angular2-color-picker/releases/tag/1.0.3
