### ISSUE TITLE
Avoid using [hidden] attribute to hide picker dialog

### ISSUE THREAD

**Issue by BrainCrumbz** [Alberplz/angular2-color-picker#71]
There are cases when the picker dialog remain visible even after the `[hidden]` attribute is set to true. According to [this post](http://www.talkingdotnet.com/dont-use-hidden-attribute-angularjs-2/) and some questions on StackOverflow, it seems like such attribute is relatively easy to break, e.g. when the same elements gets assigned a `display` value by some CSS rule.

According to same post, some of the viable alternatives would be:

> Define a css style for hidden attribute with display:none !important at the end of css stylesheet.

```css
[hidden] {
  display: none !important;
}
```

> Second solution is, let’s not use hidden attribute. You can achieve your purpose with following code.

```html
<p [style.display]="hideElement?'none':'inherit'">
   I am using hidden.
</p>
```

**Comment by cmckni3** [comment]
This is very true.

Usually the recommendation is to use `ngIf` but `ngIf`. I think the `ngIf` may flicker upon showing and using the CSS `display` property is better.

**Comment by prystoynyy** [comment]
Hi!

This is true, but `[hidden]="!show"` isn't working in IE10.

My solution:
 1. use custom attribute `[attr.data-hidden]="!show"`
 2. apply css rule for this attribute `[data-hidden="true"] { display: none !important; }`
