### ISSUE TITLE
Rezising

### ISSUE THREAD

**Issue by haakotsm** [Alberplz/angular2-color-picker#73]
The color picker bar doesn't scale well with increased width, it's still operating as if it was 230px (default) size. This is only a visual bug as you can still pick any color range you want, it just stops what looks like half ways. 

Also I get a lot of errors if I try to put the picker inside divs with *ngIf. Cannot find property a and h in undefined

**Comment by sconix** [comment]
I have made a PR with AOT + other bug fixes, if you want to see if those are fixed in my version (I think they should) you can install the package build with my fixes by using this url: git://github.com/zefoy/angular2-color-picker.git#npm-package
