### ISSUE TITLE
Cannot read property 'getViewContainerRef' of undefined

### ISSUE THREAD

**Issue by loupi8** [Alberplz/angular2-color-picker#8]
Hi, 

I have followed the instructions in the readme, but when I click on color picker in my webpage I get this error: Uncaught (in promise): TypeError: Cannot read property 'getViewContainerRef' of undefined. Do you have any clue what could be wrong?

**Comment by Alberplz** [comment]
Hi,
What version are you using of Angular2 and color picker?
