### ISSUE TITLE
New name / release due to this project being unmaintained

### ISSUE THREAD

**Issue by sconix** [Alberplz/angular2-color-picker#80]
I plan to release direct fork of this library today under the name of 'ngx-color-picker' since this project has been now unmaintained for few months. I will gladly hand over the project back to Alberplz / welcome him as part of the development if he comes back to this project.

**Comment by Alberplz** [comment]
Im updating to 2.4

**Comment by sconix** [comment]
Let me know if you need / want any help etc.
