### ISSUE TITLE
Unable to use the package

### ISSUE THREAD

**Issue by zskhan** [Alberplz/angular2-color-picker#82]
Please move to this repo [ng-color-picker](https://github.com/zskhan/ng-color-picker)
I have updated and published as 

> ng-color-picker

 with some fixes.

**Comment by sconix** [comment]
There is an AOT compatible release coming soon for this library.

**Comment by bitconym** [comment]
@sconix can you give us an estimate for the AOT version?

**Comment by sconix** [comment]
Its not up to me, the PR is there and it works for me. I haven't heard back from Alberplz about the issue he is having with it. I have published ngx-color-picker from my PR branch which works with AOT and has couple of other bug fixes as well. I plan to keep it up to date and maybe even do some fixes / improvements. But the future of that library depends greatly about how this projects continues. I would gladly offer that name for this library (if more generic name is wante by Alberplz when Angular 4 is out) or just unpublish it when this library gets back to more active state, but if not then I might even take it on for active development with new features etc.

**Comment by bitconym** [comment]
@sconix Thanks for the fixed version, it works great!

**Comment by BrainCrumbz** [comment]
There are some questions floating around, like: Is anyone in contact with project owner? Is anyone interested in actively contributing to this? Is the owner available to empower more people to work at this? 

I'm sure there are more important things than this OSS project, but it's a pity to disperse all these people efforts in a number of project clones. Why not put all efforts together in a *single* one?.

Just our 2c.

**Comment by BBaysinger** [comment]
Sheesh, are we still waiting on a resolution to this?

**Comment by sconix** [comment]
There is a fixed version released under ngx-color-picker. It is actively maintained and will have new stuff also later on, for now its just up to date version of this library.

**Comment by GiuseppePiscopo** [comment]
@sconix could you please clarify? Do you mean some sort of "port" of this library under a different name or different feature set? And anyway, where it can be found, e.g. to make a comparison?

Thanks

**Comment by wartab** [comment]
@GiuseppePiscopo He mentioned the name of the library. Should have taken you less time type this name and Google than asking the question here.

It is a drop in replacement that is maintained and can be used with AoT compilation.

**Comment by GiuseppePiscopo** [comment]
There have been other people mentioning other alternative picker projects, not sure whether they are the same and the project is the same or not.
That's why a Google search was not enough for me (see also the other questions asked). Regards
