### ISSUE TITLE
Colorpicker inserts index.html loading instead of color picker

### ISSUE THREAD

**Issue by skunheal** [Alberplz/angular2-color-picker#9]
I have a problem with the color picker.

I use angular 2.0.0-rc.1

My app.ts:

```
import 'reflect-metadata';
import 'zone.js/dist/zone';
import { Component, provide } from '@angular/core';
import { bootstrap } from 'angular2-meteor-auto-bootstrap';
import { Parties }   from '../collections/parties';
import { Mongo }     from 'meteor/mongo';
import {SidebarComponent} from './sidebar/sidebar.component';
import { APP_BASE_HREF } from '@angular/common';
import { ROUTER_PROVIDERS, ROUTER_DIRECTIVES, RouteConfig } from '@angular/router-deprecated';
import {HomeComponent} from './home.component';
import {ColorSettingsComponent} from './settings/commonsettings.component'
import {ColorPickerDirective} from './color-picker/color-picker.directive'
import {ColorPickerService} from './color-picker/color-picker.service'


@Component({
  selector: 'app',
  templateUrl: 'client/main.template.html',
  directives: [SidebarComponent, ROUTER_DIRECTIVES, ColorPickerDirective]
})

@RouteConfig([
  {path: '/home', name: 'OtherSettings', component: HomeComponent, useAsDefault: true},
  {path: '/colorSettings/...', name: 'ColorSettings', component: ColorSettingsComponent}
])

class App {
  private color: string = "#127bdc";
}

bootstrap(App, [ColorPickerService, ROUTER_PROVIDERS, provide(APP_BASE_HREF, { useValue: '/' })]);
```

And the main.template.html
```
<router-outlet></router-outlet>
<input [(colorPicker)]="color" [style.background]="color" [value]="color"/>
```

Now when I load my app I see the input field with the color in it! But when I click on it it doesnt give me the popup with the color selector. Instead it loads reinitialize my app inside the current app.

DOM after clicking:
```
<color-picker _ngcontent-ury-6="" _nghost-ury-7="">
<html _ngcontent-ury-7="">
<head _ngcontent-ury-7="">
  <link _ngcontent-ury-7="" class="__meteor-css__" href="/merged-stylesheets.css?hash=022116d8e3adef6d19b855e9e9ca1fab0257cb78" rel="stylesheet" type="text/css">
</head>
<body _ngcontent-ury-7="">
<app _ngcontent-ury-7="">Loading</app>
```

I get no errors. And when I type #hex values in the input field the color changes accordingly. What am I doing wrong?

Greetings and thanks in advance

**Comment by DennisSmolek** [comment]
@skunheal Can you try putting it into one of your routes?
Also, did you update the directive to use the RC syntax of `'@angular/core'` vs `'angular2/core'`?

I'm on RC.1 as well and am not having the same issue but I didn't try to put the input on the root app component.

When you click on the input it fires the `DynamicComponentLoader` with `loadNextToLocation()`

Looking at [the documentation](https://angular.io/docs/ts/latest/api/core/DynamicComponentLoader-class.html) That should be loading it directly next to that input element and in mine it is acting as such but messing with that is where I would start. 

I'd pop it into a route and try it...

**Comment by Alberplz** [comment]
The plugin now is updated to rc1
