### ISSUE TITLE
this library vs ng-color-picker

### ISSUE THREAD

**Issue by dolanmiu** [Alberplz/angular2-color-picker#93]
What is the difference between the two libraries? From looking at the source of the two libraries, they seem to be exactly the same:

https://github.com/zskhan/ng-color-picker

Here is the diff:

https://www.diffchecker.com/J6AA7E8e

**Comment by BrainCrumbz** [comment]
See https://github.com/Alberplz/angular2-color-picker/issues/82 . You may probably want to close this issue afterward.
