### ISSUE TITLE
Not working with @angular/cli@1.0.0 with angular4

### ISSUE THREAD

**Issue by oztek22** [Alberplz/angular2-color-picker#99]
this is what I'm getting in error message

ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in .../node_modules/angular2-color-picker/node_modules/@angular/core/src/metadata/ng_module.d.ts,

**Comment by phmello** [comment]
I've noticed that this repo hasn't been updated since Jan 31, since I needed to keep working on my project I've forked it and resolved the issue.

This is the PR: [https://github.com/Alberplz/angular2-color-picker/pull/100](https://github.com/Alberplz/angular2-color-picker/pull/100)

cheers

**Comment by sconix** [comment]
There is up-to-date version with name ngx-color-picker. Works with Angular 4 / AOT etc. It does not have any new stuff yet, but will have at some point.

**Comment by phmello** [comment]
great stuff, thanks

**Comment by oztek22** [comment]
Thanks @sconix
